version: "3"
services:
  web_server:
    image: nginx:latest
    container_name: container_nginx
    ports:
      - 8888:80
    volumes:
      - ./config/nginx/:/etc/nginx/conf.d
      - ./src:/var/www/src
    networks:
      - test_lumen
  php_fpm_8_0_6:
    build:
      context: .
      dockerfile: DockerFiles/phpDockerFile
    container_name: container_php_fpm
    restart: unless-stopped
    volumes:
      - ./src:/var/www/src
    networks:
      - test_lumen
  native_mysql:
    image: mysql:5.7
    container_name: container_mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: test_lumen
      MYSQL_ROOT_PASSWORD: root@123
      MYSQL_PASSWORD: Leminhtam@123
      MYSQL_USER: leminhtam
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./var/lib/mysql:/var/lib/mysql
      - ./config/mysql:/etc/mysql/conf.d
    networks:
      - test_lumen
networks:
  test_lumen:
    driver: bridge